version: '3.7'
services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  api_back:
    build: ./backLocalib
    container_name: springlocalib
    restart: always
    depends_on:
      - mongo_db
    ports:
      - 8080:8080
  api_front:
    build: ./frontLocalib
    container_name: reactlocalib
    depends_on:
      - api_back
    ports:
      - 3000:3000